description: "Pipe eval test"

prompts:
  - file://prompt.py:format_image_prompt
  

providers:
  # - id: google:gemini-3-pro-preview
  # - id: google:gemini-2.5-flash
  - id: anthropic:claude-opus-4-5-20251101
  - id: anthropic:messages:claude-sonnet-4-5-20250929
  - id: anthropic:messages:claude-haiku-4-5-20251001
  # - id: openai:gpt-5-mini
  # - id: openai:o3
  # - id: openai:o4-mini
  # - id: openai:gpt-4o

evaluateOptions:
  repeat: 1
  

tests:
  - description: 'Test if output is equal to the expected value'
    vars:
      image_url: file://image/piping-red-full-1268x951-600.png
    # TODO write tests to verify coordinate location accuracy (or distance accuracy), trajectory, or final output.
    # assert:
    #   # Compare model measurements with actual values
    #   - type: python
    #     value: file://compare_values.py

