description: "Pipe eval test"

prompts:
  - file://prompt.py:format_image_prompt
  

providers:
  # - id: google:gemini-3-pro-preview
  # - id: google:gemini-2.5-flash
  # - id: anthropic:claude-opus-4-5-20251101
  - id: anthropic:messages:claude-sonnet-4-5-20250929
    config:
      max_tokens: 20000
      temperature: 1
      thinking:
        type: 'disabled'
        # budget_tokens: 16000
  # - id: anthropic:messages:claude-haiku-4-5-20251001
  #   config:
  #     max_tokens: 20000
  #     temperature: 1
  #     thinking:
  #       type: 'enabled'
  #       budget_tokens: 16000
  # - id: openai:gpt-5-mini
  # - id: openai:o3
  # - id: openai:o4-mini
  # - id: openai:gpt-4o

evaluateOptions:
  repeat: 3
  

tests:
  - description: 'Test if output is equal to the expected value'
    vars:
      image_url: file://image/piping-red-full-1268x951-600.png
    assert:
      # Test verifies pixel distance value against expected
      - type: python
        value: file://compare_values.py

